### ISSUE TITLE
labels not legible

### ISSUE THREAD

**Issue by cchapin-ms** [benc-uk/armview-web#10]
I tried using version 0.4.5 in VS Code to create an image from an ARM template, and the labels are just blobs of black. It looks like it might be writing multiple lines of words over itself. I can't find any way of correcting it. 
![arm sample](https://user-images.githubusercontent.com/65252091/128549613-e74a8395-5583-4cd6-83af-599ab53c69be.png)

**Comment by odelljl** [comment]
I'm seeing this same issue.

**Comment by benc-uk** [comment]
Should be fixed.
This project will probably no longer be updated with the decline in use of ARM templates
