### ISSUE TITLE
TemplateSpec support?

### ISSUE THREAD

**Issue by majorvin** [benc-uk/armview-web#5]
I know that using template spec will be tricky, will it be possible to "guess" and use the name of the template spec and the file name as how we do on regular linked templates?

**Comment by benc-uk** [comment]
In light of the focus on Bicep over legacy JSON ARM templates going forward, I will be putting this project into semi-hibernation from here. The Bicep extension for VS Code has great visualization built in.
As such I won't be looking at adding major new features. Sorry.
